// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkgpafmklinpamydwfrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rZ3BhZm1rbGlucGFteWR3ZnJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNTc2MjIsImV4cCI6MjA1NjkzMzYyMn0.icBYKCEWf7QZLypcOSUSVfJ-vM0G36r2WTxwo43o8lY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);